# Generated by Django 3.2.7 on 2021-10-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groovytunes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='voting',
        ),
    ]
