# Generated by Django 3.2.7 on 2021-10-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groovytunes', '0002_remove_comment_voting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment_text',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
