# Generated by Django 3.2.7 on 2021-10-08 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_comment_playlist_rated_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rated',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='rated',
            name='user',
        ),
        migrations.RemoveField(
            model_name='song',
            name='playlist',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='Rated',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
